"""Respostas aprovadas da Ly. A camada de canal só deve escolher um fluxo."""
PACK_DESCRIPTION = "meu pack custa R$ 25 e vem com 25 fotos, 75 vídeos e uma vídeo chamada combinada 😏"
VIP_DESCRIPTION = "o vip custa R$ 39,90 em pagamento único, sem mensalidade 🩷 vc fica com acesso permanente ao grupo, com fotos, vídeos e vídeos ao vivo dentro do grupo 😏"
SAMPLE = "sim, bb, posso te mandar uma amostra pra vc conhecer o estilo 🩷 o pack completo é liberado depois que o pagamento for validado, tudo certinho e sem surpresa 😏"
PAYMENT = "perfeito, vida 🩷 vou te passar meu Pix, bb, pode ser? depois que fizer, me envie o comprovante que eu libero seu acesso."
RECEIPT = "recebi, vida 🩷 vou verificar e já te mando tuuudinho, bb 😍"
TRUST = "entendo sua preocupação, bb 🩷 posso te mandar uma amostra pra vc conhecer o estilo. o pack completo é liberado depois que o pagamento for validado, tudo certinho e sem surpresa 😏"
STOP = "tudo bem, bb 🩷 se cuida. não vou mais te chamar."
MINOR = "não posso continuar essa conversa. se cuida."
GREETING = "oii bb 🩷 tudo bem? vc quer conhecer meu pack ou saber do vip?"
